
const SUPABASE_URL='https://ytwgtywxfmsjpgoytoxx.supabase.co';
const SUPABASE_KEY='sb_publishable_xiBIjgbjoI1zapG9v-nofQ_vAbIB69S';
const APP_URL='https://app.jgmechanic.co.uk';
const FIREBASE_CONFIG={apiKey:'AIzaSyAzK1oA4VgeNLx84eoNpHjUVIAccPJxU90',authDomain:'jg-mobile-mechanic.firebaseapp.com',projectId:'jg-mobile-mechanic',storageBucket:'jg-mobile-mechanic.firebasestorage.app',messagingSenderId:'707409362105',appId:'1:707409362105:web:05e00c0075ff99b0186f68'};
const FCM_VAPID_KEY='BF5X3cnm1c8CiwLtdxCUwQ4rXdF4cKeSleRK6NfM2rNWjQAKZ4Ka3gsP4hpTDFqlI7EXfuZ9cHkYCj-YVnWpUcw';
let messagingReady=true;

let token=localStorage.getItem('jg_access_token')||'', refreshToken=localStorage.getItem('jg_refresh_token')||'', role='', profile=null, loginMode='mechanic';
let db={customers:[],vehicles:[],jobs:[],invoices:[],requests:[]};
function setLoginMode(m){loginMode=m;document.getElementById('loginMsg').textContent=m==='mechanic'?'Mechanic access — full workshop system.':'Customer access — your own vehicles, history and invoices.'}
async function api(path,{method='GET',body,auth=true,headers={}}={}){let h={'apikey':SUPABASE_KEY,'Content-Type':'application/json',...headers};if(auth&&token)h.Authorization='Bearer '+token;let r=await fetch(SUPABASE_URL+path,{method,headers:h,body:body?JSON.stringify(body):undefined});let txt=await r.text(),data;try{data=txt?JSON.parse(txt):null}catch{data=txt}if(!r.ok)throw new Error(data?.message||data?.error_description||data?.hint||txt||('HTTP '+r.status));return data}
function showForgotPassword(){document.getElementById('loginView').classList.add('hidden');document.getElementById('forgotView').classList.remove('hidden');document.getElementById('forgotEmail').value=val('loginEmail')}
function backFromForgot(){document.getElementById('forgotView').classList.add('hidden');document.getElementById('loginView').classList.remove('hidden')}
async function sendPasswordReset(){let msg=document.getElementById('forgotMsg'),email=val('forgotEmail').toLowerCase();if(!email)return msg.innerHTML='<span class="bad">Please enter your email address.</span>';msg.textContent='Sending recovery email…';try{await api('/auth/v1/recover?redirect_to='+encodeURIComponent(APP_URL),{method:'POST',auth:false,body:{email}});msg.innerHTML='<span class="ok">Recovery email sent ✓ Check your inbox and click the reset link.</span>'}catch(e){msg.innerHTML='<span class="bad">Could not send reset email: '+esc(e.message)+'</span>'}}
async function saveNewPassword(){let msg=document.getElementById('resetMsg'),p=document.getElementById('newPassword').value,c=document.getElementById('confirmPassword').value;if(p.length<6)return msg.innerHTML='<span class="bad">Password must be at least 6 characters.</span>';if(p!==c)return msg.innerHTML='<span class="bad">The two passwords do not match.</span>';msg.textContent='Updating password…';try{await api('/auth/v1/user',{method:'PUT',body:{password:p}});msg.innerHTML='<span class="ok">Password updated ✓ You can now sign in with your new password.</span>';setTimeout(()=>{logout();document.getElementById('resetView').classList.add('hidden');document.getElementById('loginView').classList.remove('hidden');history.replaceState(null,'',location.pathname)},1200)}catch(e){msg.innerHTML='<span class="bad">Could not update password: '+esc(e.message)+'</span>'}}
function handleAuthCallback(){let h=new URLSearchParams(location.hash.replace(/^#/,'')),q=new URLSearchParams(location.search);let at=h.get('access_token')||q.get('access_token'),rt=h.get('refresh_token')||q.get('refresh_token'),type=h.get('type')||q.get('type');if(!at)return false;token=at;refreshToken=rt||'';localStorage.setItem('jg_access_token',token);if(refreshToken)localStorage.setItem('jg_refresh_token',refreshToken);if(type==='recovery'){document.getElementById('loginView').classList.add('hidden');document.getElementById('resetView').classList.remove('hidden');return true}history.replaceState(null,'',location.pathname);document.getElementById('loginMsg').innerHTML='<span class="ok">Email confirmed ✓ Signing you in…</span>';return false}
async function login(){let msg=document.getElementById('loginMsg');msg.textContent='Signing in…';try{let data=await api('/auth/v1/token?grant_type=password',{method:'POST',auth:false,body:{email:val('loginEmail'),password:document.getElementById('loginPassword').value}});token=data.access_token;refreshToken=data.refresh_token;localStorage.setItem('jg_access_token',token);localStorage.setItem('jg_refresh_token',refreshToken);await enterApp();if(loginMode==='mechanic'&&role!=='mechanic'){logout();throw new Error('This account is not a mechanic account. Use Customer Login instead.')}if(loginMode==='customer'&&role==='mechanic'){/* mechanic may still inspect app via mechanic mode */}}catch(e){msg.innerHTML='<span class="bad">'+esc(e.message)+'</span>'}}
async function enterApp(){let user=await api('/auth/v1/user');let ps=await api('/rest/v1/profiles?id=eq.'+encodeURIComponent(user.id)+'&select=*');profile=ps?.[0]||null;role=profile?.role||'customer';document.getElementById('loginView').classList.add('hidden');document.getElementById('appView').classList.remove('hidden');document.getElementById('logoutBtn').classList.remove('hidden');document.getElementById('userLine').textContent=(profile?.full_name||user.email)+' • '+role;document.getElementById('mechanicMenu').classList.toggle('hidden',role!=='mechanic');document.getElementById('customerMenu').classList.toggle('hidden',role==='mechanic');document.getElementById('welcomeTitle').textContent=role==='mechanic'?'Workshop Dashboard':'Customer Portal';document.getElementById('welcomeText').textContent=role==='mechanic'?'Customers, vehicles, jobs and invoices synced to the cloud.':'Your vehicles, requests, service history and invoices.';if(role!=='mechanic')await completePendingAfterLogin();await loadCloud();show(role==='mechanic'?'records':'myvehicles');updateNotificationLabels()}
function logout(){token='';refreshToken='';role='';profile=null;localStorage.removeItem('jg_access_token');localStorage.removeItem('jg_refresh_token');document.getElementById('appView').classList.add('hidden');document.getElementById('loginView').classList.remove('hidden');document.getElementById('logoutBtn').classList.add('hidden');document.getElementById('userLine').textContent=''}
async function loadCloud(){try{[db.customers,db.vehicles,db.jobs,db.invoices,db.requests]=await Promise.all([api('/rest/v1/customers?select=*&order=name'),api('/rest/v1/vehicles?select=*&order=registration'),api('/rest/v1/jobs?select=*&order=job_date.desc'),api('/rest/v1/invoices?select=*&order=invoice_date.desc'),api('/rest/v1/customer_requests?select=*&order=created_at.desc')]);refresh();document.getElementById('cloudStatus').innerHTML='<span class="ok">● Cloud sync active</span>'}catch(e){document.getElementById('cloudStatus').innerHTML='<span class="bad">Cloud error: '+esc(e.message)+'</span>';throw e}}
function show(id){document.querySelectorAll('#appView section.panel').forEach(x=>x.classList.add('hidden'));document.getElementById(id)?.classList.remove('hidden');refresh()}
function val(id){return document.getElementById(id)?.value.trim()||''}function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function clearFields(ids){ids.forEach(id=>{let e=document.getElementById(id);if(e)e.value=''})}
async function addCustomer(){if(!val('cName'))return alert('Enter customer name');let id=+val('cEditId');let body={name:val('cName'),phone:val('cPhone')||null,email:val('cEmail')||null,address:val('cAddress')||null,postcode:val('cPostcode')||null,notes:val('cNotes')||null};try{await api('/rest/v1/customers'+(id?'?id=eq.'+id:''),{method:id?'PATCH':'POST',headers:{Prefer:'return=minimal'},body});cancelCustomerEdit();await loadCloud();alert(id?'Customer updated ✓':'Customer saved to cloud ✓')}catch(e){alert('Could not save customer: '+e.message)}}
function editCustomer(id){let c=db.customers.find(x=>x.id===id);if(!c)return;show('customer');cEditId.value=c.id;cName.value=c.name||'';cPhone.value=c.phone||'';cEmail.value=c.email||'';cAddress.value=c.address||'';cPostcode.value=c.postcode||'';cNotes.value=c.notes||'';customerHeading.textContent='Edit Customer'}
function cancelCustomerEdit(){clearFields(['cEditId','cName','cPhone','cEmail','cAddress','cPostcode','cNotes']);customerHeading.textContent='Add Customer'}
async function deleteCustomer(id){if(!confirm('Delete this customer and their linked vehicles/jobs?'))return;try{await api('/rest/v1/customers?id=eq.'+id,{method:'DELETE'});await loadCloud()}catch(e){alert(e.message)}}
async function addVehicle(){if(!val('vCustomer')||!val('vReg'))return alert('Select customer and enter registration');let id=+val('vEditId');let body={customer_id:+val('vCustomer'),registration:val('vReg').toUpperCase().replace(/\s+/g,''),mileage:+val('vMiles')||null,make:val('vMake')||null,model:val('vModel')||null,year:+val('vYear')||null,engine:val('vEngine')||null,engine_code:val('vEngineCode')||null,vin:val('vVin')||null,mot_due:val('vMot')||null,service_due:val('vService')||null,notes:val('vNotes')||null};try{await api('/rest/v1/vehicles'+(id?'?id=eq.'+id:''),{method:id?'PATCH':'POST',headers:{Prefer:'return=minimal'},body});cancelVehicleEdit();await loadCloud();alert(id?'Vehicle updated ✓':'Vehicle saved to cloud ✓')}catch(e){alert('Could not save vehicle: '+e.message)}}
function editVehicle(id){let v=db.vehicles.find(x=>x.id===id);if(!v)return;show('vehicle');vEditId.value=v.id;vCustomer.value=v.customer_id;vReg.value=v.registration||'';vMiles.value=v.mileage||'';vMake.value=v.make||'';vModel.value=v.model||'';vYear.value=v.year||'';vEngine.value=v.engine||'';vEngineCode.value=v.engine_code||'';vVin.value=v.vin||'';vMot.value=v.mot_due||'';vService.value=v.service_due||'';vNotes.value=v.notes||'';vehicleHeading.textContent='Edit Vehicle'}
function cancelVehicleEdit(){clearFields(['vEditId','vReg','vMiles','vMake','vModel','vYear','vEngine','vEngineCode','vVin','vMot','vService','vNotes']);vehicleHeading.textContent='Add Vehicle'}
async function deleteVehicle(id){if(!confirm('Delete this vehicle and its jobs?'))return;try{await api('/rest/v1/vehicles?id=eq.'+id,{method:'DELETE'});await loadCloud()}catch(e){alert(e.message)}}
async function addJob(){let v=db.vehicles.find(x=>x.id===+val('jVehicle'));if(!v)return alert('Select a vehicle');let parts=+val('jParts')||0,labour=+val('jLabour')||0,id=+val('jEditId');let body={customer_id:v.customer_id,vehicle_id:v.id,job_date:val('jDate')||new Date().toISOString().slice(0,10),mileage:+val('jMiles')||null,fault_reported:val('jFault')||null,diagnosis:val('jDiagnosis')||null,work_carried_out:val('jWork')||null,parts:val('jPartsText')||null,parts_cost:parts,labour_cost:labour,total:parts+labour,payment_status:val('jPayment'),job_status:val('jStatus')||'Request Received'};try{let result=await api('/rest/v1/jobs'+(id?'?id=eq.'+id:''),{method:id?'PATCH':'POST',headers:{Prefer:id?'return=minimal':'return=representation'},body});let jobId=id||(Array.isArray(result)?result[0]?.id:null);if(jobId)await uploadJobPhotos(jobId);cancelJobEdit();await loadCloud();alert(id?'Job updated ✓':'Job saved to cloud ✓')}catch(e){alert('Could not save job: '+e.message)}}
async function uploadJobPhotos(jobId){let files=[...(jPhotos.files||[])];for(let f of files){let path=jobId+'/'+Date.now()+'-'+f.name.replace(/[^a-zA-Z0-9._-]/g,'_');let r=await fetch(SUPABASE_URL+'/storage/v1/object/job-photos/'+path,{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:'Bearer '+token,'Content-Type':f.type||'application/octet-stream'},body:f});if(!r.ok)throw new Error('Photo upload failed: '+await r.text())}}
function editJob(id){let j=db.jobs.find(x=>x.id===id);if(!j)return;show('job');jEditId.value=j.id;jVehicle.value=j.vehicle_id;jDate.value=j.job_date||'';jMiles.value=j.mileage||'';jFault.value=j.fault_reported||'';jDiagnosis.value=j.diagnosis||'';jWork.value=j.work_carried_out||'';jPartsText.value=j.parts||'';jParts.value=j.parts_cost||'';jLabour.value=j.labour_cost||'';jPayment.value=j.payment_status||'Unpaid';jStatus.value=j.job_status||'Request Received';jobHeading.textContent='Edit Job'}
function cancelJobEdit(){clearFields(['jEditId','jMiles','jFault','jDiagnosis','jWork','jPartsText','jParts','jLabour']);jPhotos.value='';jobHeading.textContent='New Job';jStatus.value='Request Received';jDate.value=new Date().toISOString().slice(0,10)}
async function deleteJob(id){if(!confirm('Delete this job?'))return;try{await api('/rest/v1/jobs?id=eq.'+id,{method:'DELETE'});await loadCloud()}catch(e){alert(e.message)}}
async function createInvoice(){let j=db.jobs.find(x=>x.id===+val('iJob'));if(!j)return alert('Select a job');let num='JG-'+new Date().getFullYear()+'-'+String(Date.now()).slice(-6);try{await api('/rest/v1/invoices',{method:'POST',headers:{Prefer:'return=minimal'},body:{customer_id:j.customer_id,vehicle_id:j.vehicle_id,job_id:j.id,invoice_number:num,invoice_date:new Date().toISOString().slice(0,10),description:val('iDescription')||j.work_carried_out||j.fault_reported||'Vehicle repair/service',subtotal:+j.total||0,total:+j.total||0,payment_status:val('iPayment'),payment_method:val('iMethod')||null,paid_at:val('iPayment')==='Paid'?new Date().toISOString():null}});document.getElementById('iDescription').value='';await loadCloud();alert('Invoice '+num+' saved ✓')}catch(e){alert('Could not save invoice: '+e.message)}}
function refresh(){let cs=db.customers.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');if(document.getElementById('vCustomer'))vCustomer.innerHTML=cs||'<option value="">Add customer first</option>';let vs=db.vehicles.map(v=>`<option value="${v.id}">${esc(v.registration)} — ${esc(v.make||'')} ${esc(v.model||'')}</option>`).join('');if(document.getElementById('jVehicle'))jVehicle.innerHTML=vs||'<option value="">Add vehicle first</option>';if(document.getElementById('iJob'))iJob.innerHTML=db.jobs.map(j=>{let v=db.vehicles.find(x=>x.id===j.vehicle_id);return `<option value="${j.id}">${esc(j.job_date||'')} — ${esc(v?.registration||'Vehicle')} — £${Number(j.total||0).toFixed(2)}</option>`}).join('');if(document.getElementById('jDate')&&!val('jDate'))jDate.value=new Date().toISOString().slice(0,10);renderRecords();renderCustomerList();renderVehicleList();renderCustomerPortal();renderMyRequests();renderInvoices();renderReminders();renderRequests()}
function renderRecords(){let el=document.getElementById('recordOut');if(!el)return;let q=(document.getElementById('search')?.value||'').toLowerCase();let jobs=db.jobs.filter(j=>{let v=db.vehicles.find(x=>x.id===j.vehicle_id)||{},c=db.customers.find(x=>x.id===j.customer_id)||{};return [v.registration,v.make,v.model,c.name,j.work_carried_out,j.fault_reported,j.diagnosis].join(' ').toLowerCase().includes(q)});if(role!=='mechanic'){el.innerHTML=jobs.map(j=>{let v=db.vehicles.find(x=>x.id===j.vehicle_id)||{};return `<div class="customer-card" style="cursor:pointer" onclick="openJobDetails(${j.id})"><b>${esc(v.registration||'Vehicle')} — ${esc(j.job_status||'Request Received')}</b><br><small>${esc(j.job_date||'')} • ${esc(j.mileage||v.mileage||'')} miles</small><p>${esc(j.work_carried_out||j.fault_reported||'Open to view job details')}</p><small style="color:var(--gold)">Open job record →</small></div>`}).join('')||'<p>No service history yet.</p>';return}let rows=jobs.map(j=>{let v=db.vehicles.find(x=>x.id===j.vehicle_id)||{},c=db.customers.find(x=>x.id===j.customer_id)||{};return `<tr><td>${esc(j.job_date||'')}</td><td><b>${esc(v.registration||'')}</b><br><small>${esc(v.make||'')} ${esc(v.model||'')}</small></td><td>${esc(c.name||'')}</td><td>${esc(j.work_carried_out||j.fault_reported||'')}</td><td>£${Number(j.total||0).toFixed(2)}</td><td><b>${esc(j.job_status||'Request Received')}</b><br><small>Payment: ${esc(j.payment_status||'')}</small></td><td><div class="actions"><button onclick="openJobDetails(${j.id})">Open</button><button onclick="editJob(${j.id})">Edit</button><button class="danger" onclick="deleteJob(${j.id})">Delete</button></div></td></tr>`}).join('');el.innerHTML=`<table><thead><tr><th>Date</th><th>Vehicle</th><th>Customer</th><th>Work</th><th>Total</th><th>Status</th><th>Actions</th></tr></thead><tbody>${rows||'<tr><td colspan="7">No jobs yet.</td></tr>'}</tbody></table>`}
function renderCustomerList(){let el=document.getElementById('customerList');if(!el||role!=='mechanic')return;el.innerHTML='<h3>Customers</h3>'+db.customers.map(c=>`<div class="customer-card"><b>${esc(c.name)}</b><br><small>${esc(c.phone||'')} ${esc(c.email||'')}</small><div class="actions"><button onclick="editCustomer(${c.id})">Edit</button><button class="danger" onclick="deleteCustomer(${c.id})">Delete</button></div></div>`).join('')}
function renderCustomerPortal(){let ve=document.getElementById('myVehicleOut'),ie=document.getElementById('myInvoiceOut');if(ve)ve.innerHTML=db.vehicles.map(v=>`<div class="customer-card"><b>${esc(v.registration)}</b> — ${esc(v.make||'')} ${esc(v.model||'')}<br><small>${v.year?esc(v.year)+' • ':''}Mileage: ${esc(v.mileage||'')} • MOT due: ${esc(v.mot_due||'—')} • Service due: ${esc(v.service_due||'—')}</small></div>`).join('')||'<p>No vehicles linked to this account yet.</p>';if(ie)ie.innerHTML=db.invoices.map(i=>`<div class="customer-card" style="cursor:pointer" onclick="openInvoiceDetails(${i.id})"><b>${esc(i.invoice_number||'Invoice')}</b> — £${Number(i.total||0).toFixed(2)}<br><small>${esc(i.invoice_date||'')} • ${esc(i.payment_status||'')}</small><br><small style="color:var(--gold)">Open invoice →</small></div>`).join('')||'<p>No invoices yet.</p>'}
function renderInvoices(){let el=document.getElementById('invoiceList');if(!el||role!=='mechanic')return;el.innerHTML='<h3>Saved Invoices</h3>'+db.invoices.map(i=>`<div class="customer-card"><b>${esc(i.invoice_number||'')}</b> — £${Number(i.total||0).toFixed(2)} — ${esc(i.payment_status||'')}<div class="actions"><button onclick="printInvoice(${i.id})">Print / PDF</button><button class="danger" onclick="deleteInvoice(${i.id})">Delete</button></div></div>`).join('')}

function renderVehicleList(){let el=document.getElementById('vehicleList');if(!el||role!=='mechanic')return;el.innerHTML='<h3>Vehicles</h3>'+db.vehicles.map(v=>{let c=db.customers.find(x=>x.id===v.customer_id)||{};return `<div class="customer-card"><b>${esc(v.registration)}</b> — ${esc(v.make||'')} ${esc(v.model||'')}<br><small>${esc(c.name||'')} • ${esc(v.mileage||'')} miles</small><div class="actions"><button onclick="editVehicle(${v.id})">Edit</button><button class="danger" onclick="deleteVehicle(${v.id})">Delete</button></div></div>`}).join('')}
function renderReminders(){let el=document.getElementById('reminderOut');if(!el)return;let today=new Date();let limit=new Date(today);limit.setDate(limit.getDate()+60);let items=[];db.vehicles.forEach(v=>[['MOT',v.mot_due],['Service',v.service_due]].forEach(([type,d])=>{if(!d)return;let dt=new Date(d+'T12:00:00');if(dt<=limit){let c=db.customers.find(x=>x.id===v.customer_id)||{};let days=Math.ceil((dt-today)/86400000);items.push({dt,type,v,c,days})}}));items.sort((a,b)=>a.dt-b.dt);el.innerHTML=items.map(x=>`<div class="customer-card reminder"><b>${esc(x.v.registration)} — ${x.type}</b><br>${esc(x.c.name||'')}<br><small>Due ${esc(x.dt.toLocaleDateString('en-GB'))} • ${x.days<0?Math.abs(x.days)+' days overdue':x.days+' days remaining'}</small></div>`).join('')||'<p>No MOT/service dates due within 60 days.</p>'}
async function deleteInvoice(id){if(!confirm('Delete this invoice?'))return;try{await api('/rest/v1/invoices?id=eq.'+id,{method:'DELETE'});await loadCloud()}catch(e){alert(e.message)}}
function printInvoice(id){let i=db.invoices.find(x=>x.id===id),c=db.customers.find(x=>x.id===i.customer_id)||{},v=db.vehicles.find(x=>x.id===i.vehicle_id)||{},j=db.jobs.find(x=>x.id===i.job_id)||{};let w=window.open('','_blank');w.document.write(`<!doctype html><html><head><title>${esc(i.invoice_number)}</title><style>body{font-family:Arial;padding:35px;color:#111}header{display:flex;align-items:center;border-bottom:3px solid #d49a00;padding-bottom:15px}img{width:100px;height:100px;border-radius:50%}h1{margin-left:20px}table{width:100%;border-collapse:collapse;margin-top:25px}td,th{padding:10px;border-bottom:1px solid #ccc;text-align:left}.total{text-align:right;font-size:22px;font-weight:bold;margin-top:25px}</style></head><body><header><img src="logo.png"><h1>JG MOBILE MECHANIC<br><small>INVOICE ${esc(i.invoice_number||'')}</small></h1></header><p><b>Date:</b> ${esc(i.invoice_date||'')}</p><p><b>Customer:</b> ${esc(c.name||'')}<br>${esc(c.address||'')} ${esc(c.postcode||'')}<br>${esc(c.phone||'')} ${esc(c.email||'')}</p><p><b>Vehicle:</b> ${esc(v.registration||'')} — ${esc(v.make||'')} ${esc(v.model||'')}<br><b>Mileage:</b> ${esc(j.mileage||v.mileage||'')}</p><table><tr><th>Description</th><th>Parts</th><th>Labour</th></tr><tr><td>${esc(i.description||j.work_carried_out||'Vehicle repair/service')}</td><td>£${Number(j.parts_cost||0).toFixed(2)}</td><td>£${Number(j.labour_cost||0).toFixed(2)}</td></tr></table><div class="total">TOTAL: £${Number(i.total||0).toFixed(2)}</div><p><b>Payment:</b> ${esc(i.payment_status||'')} ${i.payment_method?'— '+esc(i.payment_method):''}</p><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
async function getJobPhotoUrls(jobId){try{let r=await fetch(SUPABASE_URL+'/storage/v1/object/list/job-photos',{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({prefix:String(jobId)+'/',limit:100,offset:0,sortBy:{column:'created_at',order:'asc'}})});if(!r.ok)return[];let files=await r.json(),urls=[];for(let f of files){if(!f.name)continue;let path=String(jobId)+'/'+f.name;let sr=await fetch(SUPABASE_URL+'/storage/v1/object/sign/job-photos/'+encodeURIComponent(path).replace(/%2F/g,'/'),{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({expiresIn:3600})});if(sr.ok){let x=await sr.json();let u=x.signedURL||x.signedUrl;if(u)urls.push(u.startsWith('http')?u:SUPABASE_URL+'/storage/v1'+u)}}return urls}catch(e){console.warn('Could not load job photos',e);return[]}}
async function openJobDetails(id){let j=db.jobs.find(x=>x.id===id);if(!j)return;let v=db.vehicles.find(x=>x.id===j.vehicle_id)||{},c=db.customers.find(x=>x.id===j.customer_id)||{};show('jobdetail');let el=document.getElementById('jobDetailOut');el.innerHTML=`<button class="secondary no-print" onclick="show('records')">← Back to Service History</button><h2>${esc(v.registration||'Vehicle')} — Job Record</h2><div class="customer-card"><b>Status:</b> ${esc(j.job_status||'Request Received')}<br><small>${esc(j.job_date||'')} • ${esc(j.mileage||v.mileage||'')} miles</small></div><p><b>Reported fault / request</b><br>${esc(j.fault_reported||'—')}</p><p><b>Diagnosis</b><br>${esc(j.diagnosis||'—')}</p><p><b>Work carried out</b><br>${esc(j.work_carried_out||'—')}</p><p><b>Parts fitted / used</b><br>${esc(j.parts||'—')}</p><p><b>Payment status:</b> ${esc(j.payment_status||'—')}</p><h3 style="color:var(--gold)">Progress / Job Photos</h3><div id="jobPhotoOut"><p class="muted">Loading photos…</p></div>`;let urls=await getJobPhotoUrls(id),po=document.getElementById('jobPhotoOut');if(po)po.innerHTML=urls.length?`<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:10px">${urls.map(u=>`<a href="${esc(u)}" target="_blank"><img src="${esc(u)}" style="width:100%;max-height:240px;object-fit:cover;border-radius:10px;border:1px solid var(--line)"></a>`).join('')}</div>`:'<p class="muted">No progress photos have been added yet.</p>'}
function openInvoiceDetails(id){let i=db.invoices.find(x=>x.id===id);if(!i)return;let v=db.vehicles.find(x=>x.id===i.vehicle_id)||{},j=db.jobs.find(x=>x.id===i.job_id)||{};show('invoicedetail');document.getElementById('invoiceDetailOut').innerHTML=`<button class="secondary no-print" onclick="show('myinvoices')">← Back to Invoices</button><h2>Invoice ${esc(i.invoice_number||'')}</h2><div class="customer-card"><b>${esc(v.registration||'Vehicle')}</b> — ${esc(v.make||'')} ${esc(v.model||'')}<br><small>${esc(i.invoice_date||'')} • ${esc(i.payment_status||'')}</small></div><p><b>Description</b><br>${esc(i.description||j.work_carried_out||'Vehicle repair/service')}</p><div class="row"><div class="customer-card"><b>Parts</b><br>£${Number(j.parts_cost||0).toFixed(2)}</div><div class="customer-card"><b>Labour</b><br>£${Number(j.labour_cost||0).toFixed(2)}</div></div><h2 style="text-align:right;color:var(--gold)">Total: £${Number(i.total||0).toFixed(2)}</h2><p><b>Payment:</b> ${esc(i.payment_status||'')} ${i.payment_method?'— '+esc(i.payment_method):''}</p><button onclick="printInvoice(${i.id})">Print / Save PDF</button>`}
function showCustomerRegistration(){document.getElementById('loginView').classList.add('hidden');document.getElementById('registerView').classList.remove('hidden');let e=val('loginEmail');if(e)document.getElementById('rEmail').value=e}
function backToLogin(){document.getElementById('registerView').classList.add('hidden');document.getElementById('loginView').classList.remove('hidden')}
async function submitCustomerRegistration(){let msg=document.getElementById('registerMsg'),name=val('rName'),phone=val('rPhone'),email=val('rEmail').toLowerCase(),password=document.getElementById('rPassword').value,reg=val('rReg').toUpperCase().replace(/\s+/g,''),miles=+val('rMiles')||null,make=val('rMake'),model=val('rModel'),year=+val('rYear')||null,issue=val('rIssue');if(!name||!phone||!email||password.length<6||!reg||!issue)return msg.innerHTML='<span class="bad">Please complete name, mobile, email, password, registration and vehicle issue.</span>';msg.textContent='Creating your secure account…';try{let d=await api('/auth/v1/signup?redirect_to='+encodeURIComponent(APP_URL),{method:'POST',auth:false,body:{email,password,data:{full_name:name}}});let access=d.access_token||null;if(!access){msg.innerHTML='<span class="ok">Account created. Please confirm your email if Supabase asks you to, then return here and sign in. Your vehicle request will be completed after your first login.</span>';localStorage.setItem('jg_pending_request',JSON.stringify({name,phone,email,reg,miles,make,model,year,issue}));return}token=access;refreshToken=d.refresh_token||'';localStorage.setItem('jg_access_token',token);localStorage.setItem('jg_refresh_token',refreshToken);await finishPendingRegistration({name,phone,email,reg,miles,make,model,year,issue},document.getElementById('rPhotos').files);msg.innerHTML='<span class="ok">Account and repair request created ✓ Opening your customer portal…</span>';setTimeout(()=>enterApp(),500)}catch(e){msg.innerHTML='<span class="bad">'+esc(e.message)+'</span>'}}
async function finishPendingRegistration(x,files){let user=await api('/auth/v1/user');let cs=await api('/rest/v1/customers?user_id=eq.'+encodeURIComponent(user.id)+'&select=*');let c=cs?.[0];if(!c){let byEmail=await api('/rest/v1/customers?email=ilike.'+encodeURIComponent(x.email)+'&select=*');c=byEmail?.[0]}if(!c){let created=await api('/rest/v1/customers',{method:'POST',headers:{Prefer:'return=representation'},body:{name:x.name,phone:x.phone,email:x.email,user_id:user.id}});c=created[0]}else if(!c.user_id){await api('/rest/v1/customers?id=eq.'+c.id,{method:'PATCH',headers:{Prefer:'return=minimal'},body:{user_id:user.id,phone:x.phone||c.phone}})}let vs=await api('/rest/v1/vehicles?registration=eq.'+encodeURIComponent(x.reg)+'&select=*');let v=vs?.[0];if(!v){let created=await api('/rest/v1/vehicles',{method:'POST',headers:{Prefer:'return=representation'},body:{customer_id:c.id,registration:x.reg,make:x.make,model:x.model,year:x.year,mileage:x.miles}});v=created[0]}let createdReq=await api('/rest/v1/customer_requests',{method:'POST',headers:{Prefer:'return=representation'},body:{customer_id:c.id,vehicle_id:v.id,service_type:'Repair / Problem',issue:x.issue,mileage:x.miles,status:'New'}});let req=createdReq[0];if(files?.length)for(let f of files){let path=req.id+'/'+Date.now()+'-'+f.name.replace(/[^a-zA-Z0-9._-]/g,'_');let r=await fetch(SUPABASE_URL+'/storage/v1/object/request-photos/'+path,{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:'Bearer '+token,'Content-Type':f.type||'application/octet-stream'},body:f});if(!r.ok)console.warn('Photo upload failed',await r.text())}localStorage.removeItem('jg_pending_request')}
async function completePendingAfterLogin(){let raw=localStorage.getItem('jg_pending_request');if(!raw)return;try{let x=JSON.parse(raw),u=await api('/auth/v1/user');if((u.email||'').toLowerCase()===x.email.toLowerCase())await finishPendingRegistration(x,null)}catch(e){console.warn(e)}}
function showCustomerRequestForm(){show('newrequest');populateCustomerRequestForm();renderMyRequests()}
function populateCustomerRequestForm(){let sel=document.getElementById('crVehicle');if(!sel)return;sel.innerHTML=db.vehicles.map(v=>`<option value="${v.id}">${esc(v.registration)} — ${esc(v.make||'')} ${esc(v.model||'')}</option>`).join('');if(db.vehicles.length){let v=db.vehicles[0];sel.value=v.id;document.getElementById('crMiles').value=v.mileage||''}renderPreviousWorkForRequest();sel.onchange=()=>{let v=db.vehicles.find(x=>x.id===+sel.value);document.getElementById('crMiles').value=v?.mileage||'';renderPreviousWorkForRequest()}}
function renderPreviousWorkForRequest(){let el=document.getElementById('crPreviousWork'),vehicleId=+val('crVehicle');if(!el)return;let jobs=db.jobs.filter(j=>j.vehicle_id===vehicleId);el.innerHTML=jobs.map(j=>`<div class="customer-card" style="cursor:pointer" onclick="openJobDetails(${j.id})"><b>${esc(j.job_date||'Previous job')} — ${esc(j.job_status||'')}</b><br><small>${esc(j.work_carried_out||j.diagnosis||j.fault_reported||'Open to view details')}</small><br><small style="color:var(--gold)">Open previous work →</small></div>`).join('')||'<p class="muted">No previous work recorded for this vehicle.</p>'}
function renderMyRequests(){let el=document.getElementById('myRequestOut');if(!el||role==='mechanic')return;el.innerHTML=db.requests.map(r=>{let v=db.vehicles.find(x=>x.id===r.vehicle_id)||{};return `<div class="customer-card"><b>${esc(v.registration||'Vehicle')} — ${esc(r.service_type||'Repair / Request')}</b><br><small>${esc((r.created_at||'').slice(0,10))} • ${esc(r.status||'New')} • ${esc(r.mileage||v.mileage||'')} miles</small><p>${esc(r.issue||'')}</p></div>`}).join('')||'<p>No requests sent yet.</p>'}
async function uploadRequestPhotos(requestId,files){if(!files?.length)return;for(let f of files){let path=requestId+'/'+Date.now()+'-'+Math.random().toString(36).slice(2,7)+'-'+f.name.replace(/[^a-zA-Z0-9._-]/g,'_');let r=await fetch(SUPABASE_URL+'/storage/v1/object/request-photos/'+path,{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:'Bearer '+token,'Content-Type':f.type||'application/octet-stream'},body:f});if(!r.ok)console.warn('Photo upload failed',await r.text())}}
async function submitExistingCustomerRequest(){let msg=document.getElementById('crMsg'),v=db.vehicles.find(x=>x.id===+val('crVehicle')),type=val('crType'),miles=+val('crMiles')||null,issue=val('crIssue');if(!v)return msg.innerHTML='<span class="bad">Please select a vehicle.</span>';if(!issue)return msg.innerHTML='<span class="bad">Please describe what you need.</span>';msg.textContent='Sending your request…';try{let created=await api('/rest/v1/customer_requests',{method:'POST',headers:{Prefer:'return=representation'},body:{customer_id:v.customer_id,vehicle_id:v.id,service_type:type,issue,mileage:miles,status:'New'}});let req=created?.[0];if(req)await uploadRequestPhotos(req.id,document.getElementById('crPhotos').files);if(miles&&miles!==v.mileage)await api('/rest/v1/vehicles?id=eq.'+v.id,{method:'PATCH',headers:{Prefer:'return=minimal'},body:{mileage:miles}});document.getElementById('crIssue').value='';document.getElementById('crPhotos').value='';msg.innerHTML='<span class="ok">Request sent to JG Mobile Mechanic ✓</span>';await loadCloud();show('newrequest');populateCustomerRequestForm();renderMyRequests()}catch(e){msg.innerHTML='<span class="bad">Could not send request: '+esc(e.message)+'</span>'}}
function renderRequests(){let el=document.getElementById('requestOut');if(!el||role!=='mechanic')return;let fresh=db.requests.filter(r=>r.status!=='Converted'&&r.status!=='Closed');let badge=document.getElementById('requestBadge');if(badge)badge.textContent=fresh.length?fresh.length+' new/open':'';el.innerHTML=db.requests.map(r=>{let c=db.customers.find(x=>x.id===r.customer_id)||{},v=db.vehicles.find(x=>x.id===r.vehicle_id)||{};return `<div class="customer-card"><b>${esc(v.registration||'Vehicle')} — ${esc(c.name||'Customer')}</b><br><small>${esc(c.phone||'')} • ${esc(c.email||'')} • ${esc(r.mileage||v.mileage||'')} miles${v.year?' • '+esc(v.year):''}</small><p><b>${esc(r.service_type||'Repair / Request')}:</b><br>${esc(r.issue||'')}</p><small>Status: ${esc(r.status||'New')} • ${esc((r.created_at||'').slice(0,10))}</small><div class="actions">${r.status!=='Converted'?`<button onclick="convertRequest(${r.id})">Convert to Job</button>`:''}<button class="secondary" onclick="setRequestStatus(${r.id},'Closed')">Close</button></div></div>`}).join('')||'<p>No customer requests yet.</p>'}
async function convertRequest(id){let r=db.requests.find(x=>x.id===id);if(!r)return;show('job');jVehicle.value=r.vehicle_id;jMiles.value=r.mileage||'';jFault.value=(r.service_type?r.service_type+' — ':'')+(r.issue||'');jDate.value=new Date().toISOString().slice(0,10);await setRequestStatus(id,'Converted',false);alert('Request loaded into New Job. Add diagnosis/work/price, then Save Job.')}
async function setRequestStatus(id,status,reload=true){try{await api('/rest/v1/customer_requests?id=eq.'+id,{method:'PATCH',headers:{Prefer:'return=minimal'},body:{status}});let r=db.requests.find(x=>x.id===id);if(r)r.status=status;if(reload)await loadCloud();else renderRequests()}catch(e){alert(e.message)}}
async function enableNotifications(){
  if(!('Notification' in window)||!('serviceWorker' in navigator)){alert('Notifications are not supported in this browser.');return}
  try{
    let perm=await Notification.requestPermission();
    if(perm!=='granted'){alert('Notifications were not enabled. You can allow them later in your browser/site settings.');return}
    if(!window.jgFcmRegister) await new Promise((resolve,reject)=>{let t=setTimeout(()=>reject(new Error('Firebase messaging did not load.')),10000);window.addEventListener('jg-fcm-ready',()=>{clearTimeout(t);resolve()},{once:true})});
    // Firebase V3.7: use the current FID registration API. The messaging worker
    // lives at /firebase-messaging-sw.js as required by Firebase for web apps.
    let fidPromise=new Promise((resolve,reject)=>{
      if(window.jgFcmLastFid)return resolve(window.jgFcmLastFid);
      let t=setTimeout(()=>reject(new Error('Firebase registration completed but no Installation ID was returned.')),20000);
      window.addEventListener('jg-fcm-registered',e=>{clearTimeout(t);resolve(e.detail?.installationId||'')},{once:true});
    });
    await window.jgFcmRegister();
    let fid=window.jgFcmLastFid||await fidPromise;
    if(!fid)throw new Error('No Firebase Installation ID was returned.');
    let user=await api('/auth/v1/user');
    await api('/rest/v1/push_tokens?on_conflict=token',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:{user_id:user.id,token:fid,platform:'web-fid',role:role||'customer',updated_at:new Date().toISOString()}});
    localStorage.setItem('jg_push_enabled','1');updateNotificationLabels();alert('Notifications enabled ✓');
  }catch(e){alert('Could not enable notifications: '+e.message)}
}
function updateNotificationLabels(){let on=localStorage.getItem('jg_push_enabled')==='1'&&Notification.permission==='granted';['notifyTextM','notifyTextC'].forEach(id=>{let e=document.getElementById(id);if(e)e.textContent=on?'Notifications enabled ✓':'Enable phone/browser notifications'})}
let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;installBtn.classList.remove('hidden')});document.getElementById('installBtn').onclick=async()=>{if(deferred){deferred.prompt();deferred=null;installBtn.classList.add('hidden')}};
(async()=>{let recovery=handleAuthCallback();if(recovery)return;if(token){try{await enterApp()}catch(e){logout();document.getElementById('loginMsg').innerHTML='<span class="bad">Please sign in again.</span>'}}})();
