-- JG Mobile Mechanic V3.1 upgrade
-- Run once in Supabase SQL Editor.

create table if not exists public.customer_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  customer_id bigint not null references public.customers(id) on delete cascade,
  vehicle_id bigint not null references public.vehicles(id) on delete cascade,
  issue text not null,
  mileage integer,
  status text not null default 'New' check (status in ('New','In Progress','Converted','Closed'))
);

alter table public.customer_requests enable row level security;

-- Customers may create and view only their own customer record.
drop policy if exists "Customers insert own record" on public.customers;
create policy "Customers insert own record" on public.customers for insert to authenticated
with check (user_id = auth.uid());

drop policy if exists "Customers update own record" on public.customers;
create policy "Customers update own record" on public.customers for update to authenticated
using (user_id = auth.uid()) with check (user_id = auth.uid());

-- Customers may create vehicles only under their own customer record.
drop policy if exists "Customers insert own vehicles" on public.vehicles;
create policy "Customers insert own vehicles" on public.vehicles for insert to authenticated
with check (exists (select 1 from public.customers c where c.id=customer_id and c.user_id=auth.uid()));

drop policy if exists "Customers update own vehicles" on public.vehicles;
create policy "Customers update own vehicles" on public.vehicles for update to authenticated
using (exists (select 1 from public.customers c where c.id=customer_id and c.user_id=auth.uid()))
with check (exists (select 1 from public.customers c where c.id=customer_id and c.user_id=auth.uid()));

-- Repair requests: mechanic sees/manages all; customer sees/creates own.
drop policy if exists "Mechanic full access requests" on public.customer_requests;
create policy "Mechanic full access requests" on public.customer_requests for all to authenticated
using (public.is_mechanic()) with check (public.is_mechanic());

drop policy if exists "Customers view own requests" on public.customer_requests;
create policy "Customers view own requests" on public.customer_requests for select to authenticated
using (exists (select 1 from public.customers c where c.id=customer_id and c.user_id=auth.uid()));

drop policy if exists "Customers create own requests" on public.customer_requests;
create policy "Customers create own requests" on public.customer_requests for insert to authenticated
with check (exists (select 1 from public.customers c where c.id=customer_id and c.user_id=auth.uid()));

-- Optional customer request photos.
insert into storage.buckets (id,name,public) values ('request-photos','request-photos',false)
on conflict (id) do nothing;

drop policy if exists "Customers upload request photos" on storage.objects;
create policy "Customers upload request photos" on storage.objects for insert to authenticated
with check (bucket_id='request-photos');

drop policy if exists "Mechanic manage request photos" on storage.objects;
create policy "Mechanic manage request photos" on storage.objects for all to authenticated
using (bucket_id='request-photos' and public.is_mechanic())
with check (bucket_id='request-photos' and public.is_mechanic());
