-- JG Mobile Mechanic V3.6 - push notification device registrations
create table if not exists public.push_tokens (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade,
  token text not null unique,
  platform text not null default 'web',
  role text not null default 'customer'
);

alter table public.push_tokens enable row level security;

drop policy if exists "Users manage own push tokens" on public.push_tokens;
create policy "Users manage own push tokens"
on public.push_tokens for all
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "Mechanic can view push tokens" on public.push_tokens;
create policy "Mechanic can view push tokens"
on public.push_tokens for select
to authenticated
using (public.is_mechanic());

create index if not exists push_tokens_user_id_idx on public.push_tokens(user_id);
